<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="FIS-243" name="fawry.sofAdmin.testsActions.AddUserTest" tests="7" failures="1" timestamp="21 Feb 2019 11:37:46 GMT" time="158.484" errors="0">
  <testcase name="AddUser" time="52.263" classname="fawry.sofAdmin.testsActions.AddUserTest"/>
  <testcase name="AddUser" time="50.911" classname="fawry.sofAdmin.testsActions.AddUserTest"/>
  <testcase name="AddUser" time="11.914" classname="fawry.sofAdmin.testsActions.AddUserTest"/>
  <testcase name="AddUser" time="14.033" classname="fawry.sofAdmin.testsActions.AddUserTest"/>
  <testcase name="AddUser" time="11.733" classname="fawry.sofAdmin.testsActions.AddUserTest"/>
  <testcase name="AddUser" time="11.445" classname="fawry.sofAdmin.testsActions.AddUserTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	error msg faild expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
error msg faild expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at fawry.sofAdmin.testsActions.AddUserTest.AddUser(AddUserTest.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddUser -->
  <testcase name="AddUser" time="6.185" classname="fawry.sofAdmin.testsActions.AddUserTest"/>
</testsuite> <!-- fawry.sofAdmin.testsActions.AddUserTest -->
